# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d5cfddde48a4d71e8545c043fc144499af461077a5902d09e354206615b735cf85483a585d825a939e89296b08f5c1995eb151864b00c30ff4100c7362ecb90

test:
  secret_key_base: 9992bde5e7a51bf5730fe5ade35798eb957a6292702183b30b570b56ecf176d0bab79195be94e1977d16577adf697718d67af10fd95820a0bf86bebe732c94e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
